target:
  layout: 
    - 9-4-1-c-1
    - 9-4-1-c-1-sb
    - 9-4-1-c-2
    - 9-4-1-c-2-sb
    - 9-4-1-c-3
    - 9-4-1-c-3-sb
    - 9-4-1-c-4
    - 9-4-1-c-4-sb
    - 9-4-1-c-5
    - 9-4-1-c-5-sb
    - 9-4-1-c-6
    - 9-4-1-c-6-sb
    - 9-4-1-c-7
    - 9-4-1-c-7-sb
  control_method:
    mpc:
      4-phase: false
      8-phase: false
      17-phase: false
    drl:
      macro: true
      4-phase: true
      proposed: true
    scoot: true
  performance_metrics: 
    queue_avg: true
    queue_max: false
    delay_avg: false
    delay_max: false
    speed_avg: true
    reward: true
  seed:
    fix_flg: true
    fix_value: 1
  delay_type: 1 # 1 or 2
  signal_change_weight: 
    4-phase: 12
    8-phase: 10
    17-phase: 10

figure:
  title:
    label: Comparison of Best Performance Counts
  x_axis:
    label:
      mpc:
        4-phase: 4-Phase MPC
        8-phase: 8-Phase MPC
        17-phase: 17-Phase MPC
      drl:
        macro: Macro-State DRL
        4-phase: 4-Phase DRL
        proposed: Proposed DRL
      scoot: SCOOT
  y_axis:
    label: Number of Best Performances
  legend:
    label:
      queue_avg: Queue Length
      queue_max: Maximum Queue Length
      delay_avg: Delay
      delay_max: Maximum Delay
      speed_avg: Speed
      reward: Reward
  color_palette: muted

simulator:
  num_red_steps: 1            
  simulation_time: 1000
  time_step: 2

mpc: 
  horizon: 5
  min_successive_steps: 4
  num_max_changes: 1
  remained_steps: 2
  utilize_steps: 2
  branch_gap: -3
  objective_function:
    type: waiting_vehicles
    waiting_vehicles:
      definition: 4
      leader_detection:
        type: multiple
      queue_measurement:
        type: ema
        ema:
          alpha: 0.3
      range_type: separate
    signal_change:
      type: global

scoot:
  initial:
    split: [10, 5, 10, 5]        # initial split for each phase (step)
  limits:
    cycle: 
      max: 60
      min: 20
    split:
      min: 4
  adjustment:
    split:
      normal:
        saturation:
          threshold:
            up: 0.8
            down: 0.7
          max: 1
      emergency:
        priority: [queue, blocked, pass]
        queue:
          flg: true
          threshold:
            up: 0.5               # relative queue length which the split is incremented above
            down: 0.2             # relative queue length which the split is decremented below
          max: 3                  # number of split changes allowed for each split
        pass:
          flg: true
          threshold: 2            # steps that is allowed to continue without vehicle passing the intersection
          max: 3                  # number of split changes allowed for each split
        blocked:
          flg: true
          max: 3                  # number of split changes allowed for each split
    cycle:
      normal: 
        saturation:
          threshold:
            up: 0.8
            down: 0.7
          max: 1
      emergency:
        queue:
          flg: true
          threshold: 
            up: 0.5               # relative queue length which the split is incremented above
            down: 0.2             # relative queue length which the split is decremented below
          max: 2                  # maximum steps that the cycle time is incremented or decremented
  constants:
    spillback_length: 0.8 # distance considered as spillback at the branching point (relative to the after-branch lane length) 
    flow_rate: 0.2        # initial max flow rate for each movement [veh/s]


drl:
  architecture:
    common:
      activation_function:
        leaky_relu:
          alpha: 0.01
        type: leaky_relu
      initialization:
        type: he
    proto:
      compression:
        rate:
          dueling: 1.0
          intersection: 0.5
          intersection_encoder: 5.0
          lane: 1.0
          lane_encoder: 5.0
          lanes: 0.5
          road: 1.0
          road_encoder: 5.0
          roads: 0.5
          vehicle_encoder: 5.0
          vehicles: 1.0
        type: linear
      hidden_layers:
        number:
          dueling: 2
          intersection: 1
          intersection_encoder: 2
          lane: 1
          lane_encoder: 2
          lanes: 1
          road: 1
          road_encoder: 2
          roads: 1
          vehicle_encoder: 2
          vehicles: 1
    type: proto
  duration_steps: 5
  framework:
    apex:
      buffer:
        file_capacity: 10000
        size: 200000
      td_steps: 1
    type: apex
  reward:
    common:
      gamma: 0.8
    type: waiting_vehicles
    waiting_vehicles:
      bonus:
        movement: 0.1
        pass: 1.0
      scaler:
        tanh:
          alpha: 3
        tanh_linear:
          alpha: 3
        type: tanh_linear
      weight:
        exponential:
          half: 50
        type: queue_exponential
  state:
    intersection:
      phase: true
    lane:
      length: true
      num_vehicles: true
      type: true
    road:
      delay: true
      queue: true
      route: true
      inflow: true
    vehicle:
      number: 10