target:
  layout: '7-4-1'
  control_method:
    mpc:
      4-phase: false
      8-phase: false
      17-phase: false
    drl:
      macro: true
      micro: true
    scoot: true
  performance_metrics: [
    'queue_avg',
    'queue_max',
    'delay_avg',
    'delay_max',
    'speed_avg',
  ]
  seed:
    fix_flg: true
    fix_value: 1
  signal_change_weight: 
    4-phase: 12
    8-phase: 10
    17-phase: 10
  delay_type: 1 # 1 or 2

simulator:
  num_red_steps: 1            
  simulation_time: 500
  time_step: 2

mpc: 
  horizon: 5
  min_successive_steps: 4
  num_max_changes: 1
  remained_steps: 2
  utilize_steps: 2
  branch_gap: -3
  objective_function:
    type: waiting_vehicles
    waiting_vehicles:
      definition: 4
      leader_detection:
        type: multiple
      queue_measurement:
        type: ema
        ema:
          alpha: 0.3
      range_type: separate
    signal_change:
      type: global

scoot:
  initial_parameters:          
    cycle: 40                 
    split: [10, 10, 10, 10]    
  change_steps:
    cycle: 1                 
    split: 1                 
  max_cycle: 60                
  min_split: 4                
  spacing_threshold: 20

drl:
  action:
    random_type: 1
  architecture:
    common:
      activation_function:
        leaky_relu:
          alpha: 0.01
        type: leaky_relu
      initialization:
        type: he
    proto:
      compression:
        rate:
          dueling: 1.0
          intersection: 0.5
          intersection_encoder: 5.0
          lane: 1.0
          lane_encoder: 5.0
          lanes: 0.5
          road: 1.0
          road_encoder: 5.0
          roads: 0.5
          vehicle_encoder: 5.0
          vehicles: 1.0
        type: linear
      hidden_layers:
        number:
          dueling: 2
          intersection: 1
          intersection_encoder: 2
          lane: 1
          lane_encoder: 2
          lanes: 1
          road: 1
          road_encoder: 2
          roads: 1
          vehicle_encoder: 2
          vehicles: 1
    type: proto
  data_augmentation:
    flg: true
  duration_steps: 5
  framework:
    apex:
      buffer:
        file_capacity: 10000
        priority:
          initial_value: 500
          reset:
            episode:
              interval: 10
            type: target
        size: 200000
      local_agent:
        update_interval: 10
      target_network:
        update_interval: 1000
      td_steps: 1
    type: apex
  reward:
    common:
      gamma: 0.95
    speedy_vehicles:
      threshold: 0.5
    throughput:
      baseline: 2800
    type: waiting_vehicles
    waiting_vehicles:
      bonus: 1.0
      scaler:
        tanh:
          alpha: 3
        tanh_linear:
          alpha: 3
        type: tanh_linear
      weight:
        exponential:
          half: 50
        type: exponential
  simulation_type: test
  state:
    intersection:
      phase: true
    lane:
      length: true
      num_vehicles: true
      type: true
    road:
      delay: true
      queue: true
      route: true
    vehicle:
      number: 10
  stop:
    episode: 150
    interval: 100
    type: episode
  training:
    batch:
      number: 20
      size: 128
    epoch: 1
    learning_rate: 1e-5
    norm_clip: 1.0
    threshold: 50
    weight_decay: 0.0