target:
  layout: 
    - 7-4-1
    - 7-4-1-sb
  inflow: 
    - balanced_500
    - balanced_600
    - balanced_700
    - balanced_800
    - unbalanced
    - main-minor
  worse_definition:
    rate:
      flg: true
      value: 10 # Threshold to consider deterioration (%)
    absolute:
      flg: true
      value: 18.66 # Threshold to consider deterioration (queue: meter, delay: sec, speed: km/h)
  type: 
    upper: 
      metric: phase # phase, reward, or outflow_rate
      group: worse # specific, others, worse, not_worse, all
    middle:
      metric: outflow_rate # phase, reward, or outflow_rate
      group: worse
    lower:
      metric: reward 
      group: worse
  phase_category:
    type_1: true
    type_2: true
    type_3: true
    type_4: false
    type_5: false
    type_6: false
    others: true # except for type_1, type_2, and type_3
    all: true # all types
  performance_metric: queue_avg # queue_avg, delay_avg, speed_avg
  start_time: 50
  seed:
    fix_flg: true
    fix_value: 1
  delay_type: 1 # 1 or 2
  signal_change_weight: 
    4-phase: 12
    8-phase: 10
    17-phase: 10
  specific:
    layout: 7-4-1-sb
    inflow: balanced_800
    intersection: 5

figure:
  title:
    outflow_rate: Phase-Specific Outflow Rate
    phase: Phase Selection Ratio
    reward: Phase-Specific Average Reward
  x_axis:
    title: ''
    label:
      scoot: SCOOT
      mpc:
        4-phase: 4-Phase MPC
        8-phase: 8-Phase MPC
        17-phase: 17-Phase MPC
      drl:
        macro: Macro-State DRL
        4-phase: 4-Phase DRL
        proposed: Proposed DRL
  y_axis:
    label:
      outflow_rate: Outflow Rate [veh/h]
      reward: Average Reward
      phase: Selection Ratio
    lim: 
      outflow_rate: 300
      reward: 0.1
      phase: 0.1
  legend:
    title: Phase Type
    label:
      type_1: Type 1
      type_2: Type 2
      type_3: Type 3
      others: Others
      all: Total
  bar:
    width: 
      outflow_rate: 0.15
      reward: 0.15
      phase: 0.2
  color_palette: muted # Set2, husl, pastels, deep, muted, bright, dark, colorblind

simulator:
  num_red_steps: 1            
  simulation_time: 500
  time_step: 2

mpc: 
  horizon: 5
  min_successive_steps: 4
  num_max_changes: 1
  remained_steps: 2
  utilize_steps: 2
  branch_gap: -3
  objective_function:
    type: waiting_vehicles
    waiting_vehicles:
      definition: 4
      leader_detection:
        type: multiple
      queue_measurement:
        type: ema
        ema:
          alpha: 0.3
      range_type: separate
    signal_change:
      type: global

scoot:
  initial:
    split: [10, 5, 10, 5]        # initial split for each phase (step)
  limits:
    cycle: 
      max: 60
      min: 20
    split:
      min: 4
  adjustment:
    split:
      normal:
        saturation:
          threshold:
            up: 0.8
            down: 0.7
          max: 1
      emergency:
        priority: [queue, blocked, pass]
        queue:
          flg: true
          threshold:
            up: 0.5               # relative queue length which the split is incremented above
            down: 0.2             # relative queue length which the split is decremented below
          max: 3                  # number of split changes allowed for each split
        pass:
          flg: true
          threshold: 2            # steps that is allowed to continue without vehicle passing the intersection
          max: 3                  # number of split changes allowed for each split
        blocked:
          flg: true
          max: 3                  # number of split changes allowed for each split
    cycle:
      normal: 
        saturation:
          threshold:
            up: 0.8
            down: 0.7
          max: 1
      emergency:
        queue:
          flg: true
          threshold: 
            up: 0.5               # relative queue length which the split is incremented above
            down: 0.2             # relative queue length which the split is decremented below
          max: 2                  # maximum steps that the cycle time is incremented or decremented
  constants:
    spillback_length: 0.8 # distance considered as spillback at the branching point (relative to the after-branch lane length) 
    flow_rate: 0.2        # initial max flow rate for each movement [veh/s]

drl:
  architecture:
    common:
      activation_function:
        leaky_relu:
          alpha: 0.01
        type: leaky_relu
      initialization:
        type: he
    proto:
      compression:
        rate:
          dueling: 1.0
          intersection: 0.5
          intersection_encoder: 5.0
          lane: 1.0
          lane_encoder: 5.0
          lanes: 0.5
          road: 1.0
          road_encoder: 5.0
          roads: 0.5
          vehicle_encoder: 5.0
          vehicles: 1.0
        type: linear
      hidden_layers:
        number:
          dueling: 2
          intersection: 1
          intersection_encoder: 2
          lane: 1
          lane_encoder: 2
          lanes: 1
          road: 1
          road_encoder: 2
          roads: 1
          vehicle_encoder: 2
          vehicles: 1
    type: proto
  duration_steps: 5
  framework:
    apex:
      buffer:
        file_capacity: 10000
        size: 200000
      td_steps: 1
    type: apex
  reward:
    common:
      gamma: 0.8
    type: waiting_vehicles
    waiting_vehicles:
      bonus:
        movement: 0.1
        pass: 1.0
      scaler:
        tanh:
          alpha: 3
        tanh_linear:
          alpha: 3
        type: tanh_linear
      weight:
        exponential:
          half: 50
        type: queue_exponential
  state:
    intersection:
      phase: true
    lane:
      length: true
      num_vehicles: true
      type: true
    road:
      delay: true
      queue: true
      route: true
      inflow: true
    vehicle:
      number: 10