target:
  layout: 
    - 7-4-1
    - 7-4-1-sb
  control_method:
    mpc:
      4-phase: false
      8-phase: false
      17-phase: false
    drl:
      macro: true
      4-phase: true
      proposed: true
    scoot: true
  performance_metrics: [
    'queue_avg',
    'queue_max',
    'delay_avg',
    'delay_max',
    'speed_avg',
    'num_phase_changes',
    'reward'
  ]
  seed:
    fix_flg: true
    fix_value: 1
  delay_type: 1 # 1 or 2
  signal_change_weight: 
    4-phase: 12
    8-phase: 10
    17-phase: 10

figure:
  title:
    queue_avg: Average Queue Length 
    queue_max: Maximum Queue Length 
    delay_avg: Average Delay 
    delay_max: Maximum Delay 
    speed_avg: Average Speed 
    num_phase_changes: Number of Phase Changes 
    reward: Total Reward 
  x_axis:
    label: 
      scoot: SCOOT
      mpc:
        4-phase: 4-Phase MPC
        8-phase: 8-Phase MPC
        17-phase: 17-Phase MPC
      drl:
        macro: Macro-State DRL
        4-phase: 4-Phase DRL
        proposed: Proposed DRL
  y_axis:
    label: 
      queue_avg: Average Queue Length [m]
      queue_max: Maximum Queue Length [m]
      delay_avg: Average Delay [s]
      delay_max: Maximum Delay [s]
      speed_avg: Average Speed [km/h]
      num_phase_changes: Number of Phase Changes
      reward: Total Reward
  legend:
    title: Branch Length
    label:
      1: 50 m
      2: 30 m
    ncol: 2
  boxplot:
    color:
      palette: Set2
  stripplot:
    color:
      group:
        - id: 1
          color_id: 1
          layout: 
            - 7-4-1
        - id: 2
          color_id: 4
          layout: 
            - 7-4-1-sb
      palette: muted
    alpha: 0.6

simulator:
  num_red_steps: 1            
  simulation_time: 500
  time_step: 2

mpc: 
  horizon: 5
  min_successive_steps: 4
  num_max_changes: 1
  remained_steps: 2
  utilize_steps: 2
  branch_gap: -3
  objective_function:
    type: waiting_vehicles
    waiting_vehicles:
      definition: 4
      leader_detection:
        type: multiple
      queue_measurement:
        type: ema
        ema:
          alpha: 0.3
      range_type: separate
    signal_change:
      type: global

scoot:
  initial:
    split: [10, 5, 10, 5]        # initial split for each phase (step)
  limits:
    cycle: 
      max: 60
      min: 20
    split:
      min: 4
  adjustment:
    split:
      normal:
        saturation:
          threshold:
            up: 0.8
            down: 0.7
          max: 1
      emergency:
        priority: [queue, blocked, pass]
        queue:
          flg: true
          threshold:
            up: 0.5               # relative queue length which the split is incremented above
            down: 0.2             # relative queue length which the split is decremented below
          max: 3                  # number of split changes allowed for each split
        pass:
          flg: true
          threshold: 2            # steps that is allowed to continue without vehicle passing the intersection
          max: 3                  # number of split changes allowed for each split
        blocked:
          flg: true
          max: 3                  # number of split changes allowed for each split
    cycle:
      normal: 
        saturation:
          threshold:
            up: 0.8
            down: 0.7
          max: 1
      emergency:
        queue:
          flg: true
          threshold: 
            up: 0.5               # relative queue length which the split is incremented above
            down: 0.2             # relative queue length which the split is decremented below
          max: 2                  # maximum steps that the cycle time is incremented or decremented
  constants:
    spillback_length: 0.8 # distance considered as spillback at the branching point (relative to the after-branch lane length) 
    flow_rate: 0.2        # initial max flow rate for each movement [veh/s]

drl:
  architecture:
    common:
      activation_function:
        leaky_relu:
          alpha: 0.01
        type: leaky_relu
      initialization:
        type: he
    proto:
      compression:
        rate:
          dueling: 1.0
          intersection: 0.5
          intersection_encoder: 5.0
          lane: 1.0
          lane_encoder: 5.0
          lanes: 0.5
          road: 1.0
          road_encoder: 5.0
          roads: 0.5
          vehicle_encoder: 5.0
          vehicles: 1.0
        type: linear
      hidden_layers:
        number:
          dueling: 2
          intersection: 1
          intersection_encoder: 2
          lane: 1
          lane_encoder: 2
          lanes: 1
          road: 1
          road_encoder: 2
          roads: 1
          vehicle_encoder: 2
          vehicles: 1
    type: proto
  duration_steps: 5
  framework:
    apex:
      buffer:
        file_capacity: 10000
        size: 200000
      td_steps: 1
    type: apex
  reward:
    common:
      gamma: 0.8
    type: waiting_vehicles
    waiting_vehicles:
      bonus:
        movement: 0.1
        pass: 1.0
      scaler:
        tanh:
          alpha: 3
        tanh_linear:
          alpha: 3
        type: tanh_linear
      weight:
        exponential:
          half: 50
        type: queue_exponential
  state:
    intersection:
      phase: true
    lane:
      length: true
      num_vehicles: true
      type: true
    road:
      delay: true
      queue: true
      route: true
      inflow: true
    vehicle:
      number: 10