simulator :
  network_name: 'two_lane'
  control_method: 'drl'
  simulation_time: 500
  random_seed: 1
  time_step: 2 # シミュレーションの更新の時間幅（秒）
  red_steps: 1  # 全赤の時間（time_stepの長さに合わせ調整すること）
  min_successive_steps: 5 # 最小の青時間連続時間（ステップ数）
  max_workers: 10
  

drl:
  method: 'apex'
  learning_flg: true
  features:
    vehicle:
      position: false
      speed: false
      in_queue: true
      direction: true
    lane:
      metric: 
        num_vehicles: true
      shape:
        length: true
        type: true
    road:
      metric:
        queue_length: true
        delay: true
  num_vehicles: 5

apex:
  duration_steps: 3   # 1回の予測で決める時間幅（ステップ数） 
  td_steps: 3         # TD法の参照するステップ数
  buffer:
    size: 10000       # リプレイバッファのサイズ
    batch_size: 32    # バッチサイズ
  gamma: 0.9          # 割引率
  learning_rate: 0.01 # 学習率
  epsilon: 0.1        # 探索率（ε-greedy法）

records:
  metric:
    queue_length: true
    delay: true
    phase: true
  max_len: 20  # 記録しない場合の一次的に記録するデータの数

