simulator :
  network_name: '7-4-1'       # シミュレーションに使うネットワーク名（ディレクトリ名）（交差点数-道路数-車線数）
  control_method: 'mpc'       # 制御手法の指定
  simulation_count: 1         # シミュレーションの回数（エピソード数）
  simulation_time: 500        # シミュレーションを行う時間（秒）
  seed:
    is_random: false          # シード値をランダムにするかどうか
    value: 1                  # シード値を固定する場合の値（is_randomがfalseのときのみ有効）
  time_step: 2                # シミュレーションの更新の時間幅（秒）
  red_steps: 1                # 全赤のステップ数
  max_workers: 10             # 並列実行するワーカー数
  debug_flg: false            # デバッグモードのフラグ
  backup:
    flg: true                 # バックアップを行うかどうか
    interval: 5               # バックアップを行う頻度
  
drl:
  method: 'apex'              # DRLの手法の指定（apex）
  learning_flg: true          # 学習を行うかどうか
  duration_steps: 5           # 1回の予測で決める時間ステップ幅
  network_id: 1               # ニューラルネットワークのID
  features:                   # 特徴量について
    vehicle:                  # 自動車ごとの特徴量について
      position: true
      speed: true
      in_queue: false
      direction: true
      wait_flg: false
      near_flg: false
    lane:                     # 車線ごとの特徴量について
      metric: 
        num_vehicles: true
      shape:
        length: true
        type: true
    road:                     # 道路事の特徴量について
      metric:
        queue_length: true
        delay: true
  num_vehicles: 5              # 特徴量として取り出す1車線ごとの自動車台数
  bc_flg: false                # 行動クローンによる初期化を行うかどうか
  reward_id: 3                 # 報酬のID
  buffer_save_interval: 5      # リプレイバッファの保存間隔（エピソード数）

apex:
  td_steps: 1                  # TD法の参照するステップ数
  update_interval: 4000          # ターゲットネットワークの同期間隔
  buffer:
    num_data_for_learning: 25    # データが何個たまったら学習を行うか
    size: 300000                 # リプレイバッファのサイズ
    batch:
      number: 10               # バッチ数
      size: 128                # バッチサイズ
    initial_priority: 1000     # 初期優先度
    priority_reset_flg: false  # 優先度のリセットを行うかどうか
  num_epochs: 2                # 更新のエポック数
  gamma: 0.9                   # 割引率
  learning_rate: 1e-4          # 学習率
  weight_decay: 1e-4           # 学習時のL2正則化の重み減衰
  epsilon:                     # ε-greedy法のパラメータ
    schedule_flg: true         # ε-greedy法のεをスケジューリングを行うかどうか
    value: 0                   # スケジューリングを行わないときのεの値

bc:
  learning_flg: false          # 学習を行うかどうか
  network_id: 1                # 行動クローンを行うネットワーク構造のID
  learning_rate: 1e-5          # 学習率
  weight_decay: 1e-4           # 学習時のL2正則化の重み減衰
  batch_size: 128              # バッチサイズ
  num_epochs: 10               # エポック数  
  
mpc:
  horizon: 5                   # 予測ホライズンの長さ（ステップ数）
  utilize_steps: 2             # 採用するホライゾンの長さ（ステップ数）(horizonの半分以下)
  remained_steps: 2            # 計算を開始するときの決まってる将来のステップ数（utilize_steps以下，またhorizon > utilize_steps + remained_stepsになるようにすること）
  min_successive_steps: 4      # 最小の青時間連続時間（ステップ数）
  num_max_changes: 1           # 1回の予測での最大変化数
  bc_buffer: 
    flg: true                  # 行動クローンのためのデータ収集を行うかどうか
    size: 1000                 # 行動クローン用のバッファのひとつのファイルあたりのサイズ
    network_id: 1              # 行動クローンを行いたいネットワーク構造のID
  phases:
    - num_roads: 3
      type: '4-phase'          # 4-phaseのみ
    - num_roads: 4
      type: '17-phase'         # 4-phase, 8-phase, 17-phaseから選択
    - num_roads: 5
      type: '10-phase'         # 10-phaseのみ
  objective_type: 2            # 目的関数のタイプ（1: 信号待ち自動車数, 2: 信号待ち自動車数＋信号変化ペナルティ）
  signal_change_weight: 5      # 信号変化ペナルティの重み

scoot:
  initial_parameters:
    cycle: 40                 # サイクル時間の初期値（ステップ数）
    split: [10, 10, 10, 10]   # スプリットの初期値（ステップ数）
  change_steps:
    cycle: 1 # サイクル時間の変更時の1フェーズあたりに変化量（ステップ数）
    split: 1 # スプリット変更時のフェーズの仕切りの変化量（ステップ数）
  max_cycle: 60 # サイクル時間の最大値（ステップ数）
  min_split: 5  # 1スプリットの最小値（ステップ数）
  spacing_threshold: 40 # サイクル時間変更の閾値：何メートルに1台自動車が存在するか（密度の逆数）[m/veh]

records:
  record_flg: true             # 記録を行うかどうか
  save_folder: 'unbalanced_2222_5'         # 記録するフォルダ名（results/metrics/{mpc, drl, scoot}配下に作成される，かぶりは許容しない）
  metric:
    queue_flg: true
    delay_flg: true
    phase_flg: false
    calc_time_flg: true
  old_definition_flg: false    # 古い定義で報酬を記録するかどうか
  max_len: 20                  # 記録しない場合の一次的に記録するデータの数

