simulator :
  network_name: '9-4-1'       # シミュレーションに使うネットワーク名（ディレクトリ名）（交差点数-道路数-車線数）
  control_method: 'drl'       # 制御手法の指定
  simulation_count: 1000      # シミュレーションの回数（エピソード数）
  simulation_time: 200        # シミュレーションを行う時間（秒）
  seed:
    is_random: true           # シード値をランダムにするかどうか
    value: 1                  # シード値を固定する場合の値（is_randomがfalseのときのみ有効）
  time_step: 2                # シミュレーションの更新の時間幅（秒）
  red_steps: 1                # 全赤のステップ数
  max_workers: 10             # 並列実行するワーカー数
  debug_flg: false            # デバッグモードのフラグ
  
drl:
  method: 'apex'              # DRLの手法の指定（apex）
  learning_flg: true          # 学習を行うかどうか
  duration_steps: 5           # 1回の予測で決める時間ステップ幅
  network_id: 1               # ニューラルネットワークのID
  features:                   # 特徴量について
    vehicle:                  # 自動車ごとの特徴量について
      position: true
      speed: false
      in_queue: false
      direction: true
      wait_flg: false
      near_flg: false
    lane:                     # 車線ごとの特徴量について
      metric: 
        num_vehicles: true
      shape:
        length: true
        type: true
    road:                     # 道路事の特徴量について
      metric:
        queue_length: true
        delay: true
  num_vehicles: 5             # 特徴量として取り出す1車線ごとの自動車台数
  bc_flg: false               # 行動クローンによる初期化を行うかどうか
  reward_id: 2                # 報酬のID

apex:
  td_steps: 1               # TD法の参照するステップ数
  update_interval: 3000     # ターゲットネットワークの同期間隔
  buffer:
    learning_threshold: 50  # データが何個たまったら学習を行うか
    size: 10000             # リプレイバッファのサイズ
    batch:
      number: 10         # バッチ数
      size: 64           # バッチサイズ
  num_epochs: 3          # 更新のエポック数
  gamma: 0.9             # 割引率
  learning_rate: 1e-4    # 学習率
  weight_decay: 1e-4     # 学習時のL2正則化の重み減衰
  epsilon: 0.1           # 探索率（ε-greedy法）

bc:
  learning_flg: false     # 学習を行うかどうか
  network_id: 1           # 行動クローンを行うネットワーク構造のID
  learning_rate: 1e-4     # 学習率
  weight_decay: 1e-4      # 学習時のL2正則化の重み減衰
  batch_size: 128         # バッチサイズ
  num_epochs: 10          # エポック数  
  
mpc:
  horizon: 5              # 予測ホライズンの長さ（ステップ数）
  utilize_steps: 2        # 採用するホライゾンの長さ（ステップ数）(horizonの半分以下)
  remained_steps: 2       # 計算を開始するときの決まってる将来のステップ数（utilize_steps以下，またhorizon > utilize_steps + remained_stepsになるようにすること）
  min_successive_steps: 5 # 最小の青時間連続時間（ステップ数）
  num_max_changes: 1      # 1回の予測での最大変化数
  bc_buffer: 
    flg: true             # 行動クローンのためのデータ収集を行うかどうか
    size: 1000            # 行動クローン用のバッファのひとつのファイルあたりのサイズ
    network_id: 1         # 行動クローンを行いたいネットワーク構造のID
  phases:
    - num_roads: 3
      type: '4-phase'     # 4-phaseのみ
    - num_roads: 4
      type: '17-phase'    # 4-phase, 8-phase, 17-phaseから選択
    - num_roads: 5
      type: '10-phase'    # 10-phaseのみ

records:
  record_flg: false        # 記録を行うかどうか
  metric:
    queue_flg: true
    delay_flg: true
    phase_flg: false
    calc_time_flg: true
  max_len: 20             # 記録しない場合の一次的に記録するデータの数

