simulator :
  network_name: 'twenty_intersections' # シミュレーションに使うネットワーク名（ディレクトリ名）
  control_method: 'drl'   # 制御手法の指定
  simulation_time: 200    # シミュレーションを行う時間（秒）
  seed:
    is_random: true       # シード値をランダムにするかどうか
    value: 1              # シード値を固定する場合の値（is_randomがfalseのときのみ有効）
  time_step: 2            # シミュレーションの更新の時間幅（秒）
  red_steps: 1            # 全赤の時間（time_stepの長さに合わせ調整すること）
  min_successive_steps: 5 # 最小の青時間連続時間（ステップ数）
  max_workers: 20         # 並列実行するワーカー数
  debug_flg: false        # デバッグモードのフラグ
  

drl:
  method: 'apex'
  learning_flg: true
  features:
    vehicle:
      position: false
      speed: false
      in_queue: false
      direction: false
      wait_flg: true
      near_flg: false
    lane:
      metric: 
        num_vehicles: true
      shape:
        length: true
        type: true
    road:
      metric:
        queue_length: true
        delay: true
  num_vehicles: 10

apex:
  network_id: 1          # ニューラルネットワークのID
  duration_steps: 5      # 1回の予測で決める時間ステップ幅
  td_steps: 3            # TD法の参照するステップ数
  update_interval: 250   # ターゲットネットワークの同期間隔
  buffer:
    size: 100000         # リプレイバッファのサイズ
    batch_size: 16       # バッチサイズ
    alpha: 0.3           # 優先度をexponentialで計算する際のパラメータ
  gamma: 0.95            # 割引率
  learning_rate: 0.001   # 学習率
  epsilon: 0.5           # 探索率（ε-greedy法）

records:
  metric:
    queue_length: true
    delay: true
    phase: false
  max_len: 20  # 記録しない場合の一次的に記録するデータの数

