simulator :
  network_name: 'twenty_intersections'
  control_method: 'drl'
  simulation_time: 300
  random_seed: 1
  time_step: 2 # シミュレーションの更新の時間幅（秒）
  red_steps: 1  # 全赤の時間（time_stepの長さに合わせ調整すること）
  min_successive_steps: 5 # 最小の青時間連続時間（ステップ数）
  max_workers: 20
  

drl:
  method: 'apex'
  learning_flg: true
  features:
    vehicle:
      position: false
      speed: false
      in_queue: true
      direction: true
      go_flg: true
    lane:
      metric: 
        num_vehicles: true
      shape:
        length: true
        type: true
    road:
      metric:
        queue_length: true
        delay: true
  num_vehicles: 10

apex:
  duration_steps: 5   # 1回の予測で決める時間ステップ幅
  td_steps: 3         # TD法の参照するステップ数
  update_interval: 3  # ターゲットネットワークの同期間隔
  buffer:
    size: 100000       # リプレイバッファのサイズ
    batch_size: 256    # バッチサイズ
    alpha: 3           # Prioritized Experience Replayのα
    epsilon: 0.01      # Prioritized Experience Replayのε
  gamma: 0.9           # 割引率
  learning_rate: 0.02  # 学習率
  epsilon: 0.3         # 探索率（ε-greedy法）

records:
  metric:
    queue_length: true
    delay: true
    phase: false
  max_len: 20  # 記録しない場合の一次的に記録するデータの数

