simulator :
  network_name: 7-4-1        # シミュレーションに使うネットワーク名（ディレクトリ名）（交差点数-道路数-車線数）
  control_method: mpc        # 制御手法の指定
  num_simulations: 1        # シミュレーションの回数（エピソード数）
  simulation_time: 500       # シミュレーションを行う時間（秒）
  seed:
    is_random: false           # シード値をランダムにするかどうか
    value: 1                   # シード値（is_randomがfalseのときのみ有効，1-100を入力，検証用）
  time_step: 2                 # シミュレーションの更新の時間幅（秒）
  red_steps: 1                 # 全赤のステップ数
  max_workers: 7               # 並列実行するワーカー数
  debug: 
    flg: false                 # デバッグモードのフラグ
  backup:
    flg: true                  # バックアップを行うかどうか
    interval: 10               # バックアップを行う頻度

drl:
  method: apex                 # DRLの手法の指定
  learning_flg: true           # 学習を行うかどうか
  duration_steps: 5            # 1回の予測で決める時間ステップ幅
  network_id: 1                # ニューラルネットワークのID
  state_id: 2                  # 状態のテンプレートID
  data_augmentation_flg: true  # データ拡張を行うかどうか
  num_vehicles: 20             # 自動車台数
  reward_id: 2                 # 報酬
  done_reward: -50             # エピソード終了時のペナルティ
  bc_flg: false                # 行動クローン初期化
  save_interval: 5             # データを保存する間隔
  stop:
    flg: true                  # k回目のシミュレーションで強制終了するかどうか
    type: episode              # 'episode': エピソード数で指定, 'interval': 間隔で指定
    episode: 400               # 強制終了するエピソード数
    interval: 100              # 強制終了する間隔

apex:
  td_steps: 1                  # TD法の参照するステップ数
  update_interval: 2000        # ターゲットネットワークの同期間隔
  buffer:
    num_new_data: 25           # データが何個たまったら学習を行うか
    size: 200000               # リプレイバッファのサイズ
    batch:
      number: 20               # バッチ数
      size: 128                # バッチサイズ
    initial_priority: 500      # 初期優先度
    priority_reset: 
      flg: true                # 優先度のリセットを行うかどうか
      type: interval           # 'episode': エピソード数で指定, 'interval': 間隔で指定
      episode: 10              # 優先度をリセットするエピソード
      interval: 10             # 優先度をリセットする間隔
  num_epochs: 1                # 更新のエポック数
  gamma: 0.95                  # 割引率
  learning_rate: 1e-4          # 学習率
  weight_decay: 1e-5           # 学習時のL2正則化の重み減衰
  random_action_type: 1        # 1: 完全ランダム, 2: 自動車台数に基づいたランダム
  epsilon:                     
    schedule_flg: true         # ε-greedy法のスケジューリング
    value: 0                   # εの値（schedule_flgがfalseのとき）

bc:
  learning_flg: false          # 学習を行うかどうか
  network_id: 1                # 行動クローンを行うネットワーク構造のID
  learning_rate: 1e-5          # 学習率
  weight_decay: 1e-4           # 学習時のL2正則化の重み減衰
  batch_size: 128              # バッチサイズ
  num_epochs: 12               # エポック数  
  
mpc:
  horizon: 5                   # 予測ホライズンの長さ（ステップ数）
  utilize_steps: 2             # 採用するホライゾンの長さ（ステップ数）(horizonの半分以下)
  remained_steps: 2            # 計算を開始するときの決まってる将来のステップ数（utilize_steps以下，またhorizon > utilize_steps + remained_stepsになるようにすること）
  min_successive_steps: 4      # 最小の青時間連続時間（ステップ数）
  num_max_changes: 1           # 1回の予測での最大変化数
  bc_buffer: 
    flg: true                  # 行動クローンのためのデータ収集を行うかどうか
    size: 1000                 # 行動クローン用のバッファのひとつのファイルあたりのサイズ
    network_id: 1              # 行動クローンを行いたいネットワーク構造のID
  phases:
    - num_roads: 3
      num_phases: 4             # 4-phaseのみ
    - num_roads: 4
      num_phases: 17            # 4-phase, 8-phase, 17-phaseから選択
    - num_roads: 5
      num_phases: 10            # 10-phaseのみ
  objective_type: 2             # 目的関数のタイプ（1: 信号待ち自動車数, 2: 信号待ち自動車数＋信号変化ペナルティ）
  signal_change_weight: 20       # 信号変化ペナルティの重み

scoot:
  initial_parameters:
    cycle: 40                  # サイクル時間の初期値（ステップ数）
    split: [10, 10, 10, 10]    # スプリットの初期値（ステップ数）
  change_steps:
    cycle: 1                   # サイクル時間の変更時の1フェーズあたりに変化量（ステップ数）
    split: 1                   # スプリット変更時のフェーズの仕切りの変化量（ステップ数）
  max_cycle: 60                # サイクル時間の最大値（ステップ数）
  min_split: 5                 # 1スプリットの最小値（ステップ数）
  spacing_threshold: 40        # サイクル時間変更の閾値：何メートルに1台自動車が存在するか（密度の逆数）[m/veh]

records:
  record_flg: true              # 記録を行うかどうか
  save_folder: unbalanced_2222_20 # 記録するフォルダ名（results/metrics/{mpc, drl, scoot}配下に作成される，かぶりは許容しない）
  metric:
    queue_flg: true
    delay_flg: true
    phase_flg: true
    calc_time_flg: true
  old_definition_flg: false    # 古い定義で報酬を記録するかどうか
  max_len: 20                  # 記録しない場合の一次的に記録するデータの数

config:
  change_handle_flg: false   # シミュレーション中にconfigurationの変更を反映するかどうか

