simulator :
  network_name: 'two_lane'
  control_method: 'drl'
  simulation_time: 500
  random_seed: 1
  time_step: 2
  max_workers: 10

drl:
  method: 'a2c'
  learning_flg: true
  features:
    vehicle:
      position: false
      speed: false
      in_queue: true
      direction: true
    lane:
      metric: 
        num_vehicles: true
      shape:
        length: true
        type: true
    road:
      metric:
        queue_length: true
        delay: true
  num_vehicles: 5
