simulator :
  network_name: 'two_lane'
  control_method: 'drl'
  simulation_time: 500
  random_seed: 1
  time_step: 2
  max_workers: 10

drl:
  method: 'a2c'
  learning_flg: true
  features:
    vehicle:
      position: true
      speed: true
      in_queue: true
      direction: true
    lane:
      queue: true
      delay: true
      num_vehicles: true
  num_vehicles: 5
