simulator:
  control_method : mpc            # mpc, drl, scoot
  layout_name : 9-4-1-c-uni               # layout folder name
  inflow_name : balanced_700          # inflow file name
  num_simulations: 1                # number of simulations to run
  simulation_time: 1000              # simulation time for each simulation (seconds)
  seed:
    is_random: false                # whether to decide seed randomly or not (if is_random is true, seed value is selected from over 100.)
    value: 1                        # if is_random is false, this value is used (you should select from 1 to 100.)
  time_step: 2                      # descrete time in the simulator (seconds)
  num_red_steps: 1                  # number of red steps between phases
  max_workers: 7                    # the number of parallel workers
  debug: 
    flg: false                      # flg for debugging
  backup:
    flg: true                   
    interval: 100                  
  config_change:
    flg: true                       # if true, you can change config during simulation usually used in drl experiments

drl:
  method: apex                 # DRLの手法の指定
  learning_flg: true           # 学習を行うかどうか
  duration_steps: 5            # 1回の予測で決める時間ステップ幅
  network_id: 1                # ニューラルネットワークのID
  state_id: 2                  # 状態のテンプレートID
  data_augmentation_flg: true  # データ拡張を行うかどうか
  num_vehicles: 20             # 自動車台数
  reward_id: 2                 # 報酬
  done_reward: -50             # エピソード終了時のペナルティ
  bc_flg: false                # 行動クローン初期化
  save_interval: 5             # データを保存する間隔
  stop:
    flg: true                  # k回目のシミュレーションで強制終了するかどうか
    type: episode              # 'episode': エピソード数で指定, 'interval': 間隔で指定
    episode: 400               # 強制終了するエピソード数
    interval: 100              # 強制終了する間隔

apex:
  td_steps: 1                  # TD法の参照するステップ数
  update_interval: 2000        # ターゲットネットワークの同期間隔
  buffer:
    num_new_data: 25           # データが何個たまったら学習を行うか
    size: 200000               # リプレイバッファのサイズ
    batch:
      number: 20               # バッチ数
      size: 128                # バッチサイズ
    initial_priority: 500      # 初期優先度
    priority_reset: 
      flg: true                # 優先度のリセットを行うかどうか
      type: interval           # 'episode': エピソード数で指定, 'interval': 間隔で指定
      episode: 10              # 優先度をリセットするエピソード
      interval: 10             # 優先度をリセットする間隔
  num_epochs: 1                # 更新のエポック数
  gamma: 0.95                  # 割引率
  learning_rate: 1e-4          # 学習率
  weight_decay: 1e-5           # 学習時のL2正則化の重み減衰
  random_action_type: 1        # 1: 完全ランダム, 2: 自動車台数に基づいたランダム
  epsilon:                     
    schedule_flg: true         # ε-greedy法のスケジューリング
    value: 0                   # εの値（schedule_flgがfalseのとき）

bc:
  learning_flg: false          # 学習を行うかどうか
  network_id: 1                # 行動クローンを行うネットワーク構造のID
  learning_rate: 1e-5          # 学習率
  weight_decay: 1e-4           # 学習時のL2正則化の重み減衰
  batch_size: 128              # バッチサイズ
  num_epochs: 12               # エポック数  
  
mpc:
  horizon: 5                  # predictive horizon
  utilize_steps: 2             # number of steps acutually used in optimized steps (<= horizon / 2)
  remained_steps: 2            # number of remained steps when the optimization starts (<= utilized_steps)
  min_successive_steps: 4      # minimum steps for consecutive phases
  num_max_changes: 1           # maximum number of phase changes within a single optimization 
  branch_gap: -3                # to avoid errors between vissim and mpc regarding the branching point
  bc_buffer: 
    flg: false                  # flg of saving data for behavioral cloning
    size: 1000                  # size of dataset for each buffer file
    network_id: 1               # network architecture id for behavioral cloning
  phases:
    3-road: 4                     # only 4
    4-road: 4                     # 4, 8, or 17
    5-road: 10                    # only 10
  objective_function:
    type: waiting_vehicles        # only waiting_vehicles
    waiting_vehicles:
      definition: 4             # 1: delta_w2 is calculated with using delta_p, 2: delta_w2 is calculated without using delta_p, 3: delta_w1 and delta_w2 are both calculated without using delta_p 4: devide delta_w2 into separete binaries for before branching point and after branching point
      range_type: separate      # common: use common range for all roads, separate: use separate range for each route 
      queue_measurement:
        type: ema               # vissim: use vissim's built-in function, ema: use exponential moving average
        ema:  
          alpha: 0.3
      leader_detection:
        type: multiple                 # single: detect leader vehicle from the lane which the car go out, multiple: detect leader vehicle from multiple lanes
    signal_change:
      type: global                # global: use the signal-change binary for whole intersection, local: use the signal-change binary for each route
      weight: 12                  # weights for the term of signal change penalty

scoot:
  initial_parameters:          
    cycle: 40                  # initial cycle time (step)
    split: [10, 10, 10, 10]    # initial split for each phase (step)
  change_steps:
    cycle: 1                   # change amount of cycle time (step)
    split: 1                   # cahnge amount of split (step)
  max_cycle: 60                # max cycle time (step)
  min_split: 4                 # min split for each phase (step)
  spacing_threshold: 20        # spacing threshold for deciding whether increase or decrease cycle time
    
save:
  common:
    performance_metrics:        
      queue: true
      delay: true
      speed: true
      calc_time: true
      phase: true
    road_scale_flg: true 
  drl:
    model: true
    buffer: true


