simulator:
  control_method : drl              # mpc, drl, scoot
  seed: 1                           # random seed for vissim
  layout_name : 7-4-1               # layout folder name
  inflow_name : balanced_500        # inflow file name
  simulation_time: 500              # simulation time for each simulation (seconds)
  time_step: 2                      # descrete time in the simulator (seconds)
  num_red_steps: 1                  # number of red steps between phases
  max_workers: 7                    # the number of parallel workers
  debug: 
    flg: false                      # flg for debugging                
  config_change:
    flg: false                      # if true, you can change config during simulation usually used in drl experiments

drl:
  simulation_type: test # train or test
  stop: 
    type: episode # episode or interval
    episode: 150
    interval: 100
  training:
    learning_rate: 1e-5        # learning rate for drl
    threshold: 50              # the number of new data for each learning update
    batch:
      number: 20                 # batch number for learning
      size: 128                  # batch size for learning
    epoch: 1                     # epoch for learning
    weight_decay: 0.0            # weight decay for learning
    norm_clip: 1.0              # max norm for gradient clipping
  framework: 
    type: apex
    apex:
      td_steps: 1
      local_agent:
        update_interval: 10
      target_network:
        update_interval: 1000
      buffer:
        size: 200000
        file_capacity: 10000
        priority:
          initial_value: 500
          reset:
            type: target # episode or target or none
            episode:
              interval: 10
  duration_steps: 5
  state:
    vehicle:
      number : 10
      position: true
      speed: true
      route: true
    lane:
      length: true
      type: true
      num_vehicles: true
    road:
      queue: true
      delay: true
      route: true
    intersection:
      phase: true
  action:
    random_type: 1 # 1: completely random, 2: random based on the number of vehicles
  reward: 
    type: waiting_vehicles # waiting_vehicles, speedy_vehicles, throughput
    common:
      gamma: 0.95
    waiting_vehicles:
      bonus: 1.0 # bonus for passing through the intersection
      weight:
        type: exponential # exponential or null
        exponential:
          half: 50 # the unit is meters
      scaler:
        type: tanh_linear # tanh, tanh_linear or null
        tanh:
          alpha: 3
        tanh_linear:
          alpha: 3
    speedy_vehicles:
      threshold: 0.5
    throughput:
      baseline: 2800 # veh/h
  architecture:
    type: proto # proto only
    proto:
      hidden_layers:
        number:
          vehicle_encoder: 2
          vehicles: 1
          lane_encoder: 2
          lane: 1
          lanes: 1
          road_encoder: 2
          road: 1
          roads: 1
          intersection_encoder: 2
          intersection: 1
          dueling: 2
      compression:
        type: linear # linear or geometric
        rate: 
          vehicle_encoder: 5.0
          vehicles: 1.0
          lane_encoder: 5.0
          lane: 1.0
          lanes: 0.5
          road_encoder: 5.0
          road: 1.0
          roads: 0.5
          intersection_encoder: 5.0
          intersection: 0.5
          dueling: 1.0
    common:
      initialization:
        type: he # null or he
      activation_function:
        type: leaky_relu # relu or leaky_relu
        leaky_relu:
          alpha: 0.01
  data_augmentation:
    flg: true
  
mpc:
  horizon: 5                  # predictive horizon
  utilize_steps: 2             # number of steps acutually used in optimized steps (<= horizon / 2)
  remained_steps: 2            # number of remained steps when the optimization starts (<= utilized_steps)
  min_successive_steps: 4      # minimum steps for consecutive phases
  num_max_changes: 1           # maximum number of phase changes within a single optimization 
  branch_gap: -3                # to avoid errors between vissim and mpc regarding the branching point
  bc_buffer: 
    flg: false                  # flg of saving data for behavioral cloning
    size: 1000                  # size of dataset for each buffer file
    network_id: 1               # network architecture id for behavioral cloning
  phases:
    3-road: 4                     # only 4
    4-road: 4                     # 4, 8, or 17
    5-road: 10                    # only 10
  objective_function:
    type: waiting_vehicles        # only waiting_vehicles
    waiting_vehicles:
      definition: 4             # 1: delta_w2 is calculated with using delta_p, 2: delta_w2 is calculated without using delta_p, 3: delta_w1 and delta_w2 are both calculated without using delta_p 4: devide delta_w2 into separete binaries for before branching point and after branching point
      range_type: separate      # common: use common range for all roads, separate: use separate range for each route 
      queue_measurement:
        type: ema               # vissim: use vissim's built-in function, ema: use exponential moving average
        ema:  
          alpha: 0.3
      leader_detection:
        type: multiple                 # single: detect leader vehicle from the lane which the car go out, multiple: detect leader vehicle from multiple lanes
    signal_change:
      type: global                # global: use the signal-change binary for whole intersection, local: use the signal-change binary for each route
      weight: 12                  # weights for the term of signal change penalty

scoot:
  initial_parameters:          
    cycle: 40                  # initial cycle time (step)
    split: [10, 10, 10, 10]    # initial split for each phase (step)
  change_steps:
    cycle: 1                   # change amount of cycle time (step)
    split: 1                   # cahnge amount of split (step)
  max_cycle: 60                # max cycle time (step)
  min_split: 4                 # min split for each phase (step)
  spacing_threshold: 20        # spacing threshold for deciding whether increase or decrease cycle time
    
save:
  common:
    performance_metrics:        
      queue: true
      delay: true
      speed: true
      calc_time: true
      phase: true
    road_scale_flg: true 
  drl:
    model: true
    buffer: true


