size: [16, 9]
dpi: 
  save: 100
  display: 100
font: 
  family: sans # sans, serif
  mathtext: regular
  size: 18
axes:
  title:
    size: 24
    weight: bold # normal, bold
  label:
    size: 20
    weight: bold # normal, bold
  linewidth: 3
  grid:
    flg: true
    style: --
    alpha: 0.5
  spines:
    top: true
    right: true
legend: 
  fontsize: 16
ticks: 
  label:
    size: 16
  direction: out # in, out, inout
  major:
    width: 3
    size: 8
  minor:
    width: 1.5
    size: 4
lines:
  width: 2
  markersize: 6