size: [16, 9]
dpi: 
  save: 100
  display: 100
font: 
  family: serif # sans, serif
  mathtext: regular
  size: 32
axes:
  title:
    size: 32
    weight: bold # normal, bold
    pad: 20
  label:
    size: 32
    weight: normal # normal, bold
    pad: 15
  linewidth: 3
  grid:
    flg: true
    style: --
    alpha: 1.0
  spines:
    top: true
    right: true
legend: 
  fontsize: 28
ticks: 
  label:
    size: 28
  direction: in # in, out, inout
  major:
    width: 3
    size: 8
    pad: 10
  minor:
    width: 1.5
    size: 4
    pad: 10
lines:
  width: 4
  markersize: 6