figure:
  title: 
    7-4-1: Total Reward Transition (50m Right-turn Lane)
    7-4-1-sb: Total Reward Transition (30m Right-turn Lane)
  x_axis:
    label: Relative Episode
  y_axis:
    label: Total Reward
  legend:
    title: Inflow Pattern
    labels: 
      balanced_500: Balanced I
      balanced_600: Balanced II
      balanced_700: Balanced III
      balanced_800: Balanced IV
      main-minor: Unbalanced I
      unbalanced: Unbalanced II
    ncol: 2
    loc: lower right

simulator:
  num_red_steps: 1            
  time_step: 2

drl:
  architecture:
    common:
      activation_function:
        leaky_relu:
          alpha: 0.01
        type: leaky_relu
      initialization:
        type: he
    proto:
      compression:
        rate:
          dueling: 1.0
          intersection: 0.5
          intersection_encoder: 5.0
          lane: 1.0
          lane_encoder: 5.0
          lanes: 0.5
          road: 1.0
          road_encoder: 5.0
          roads: 0.5
          vehicle_encoder: 5.0
          vehicles: 1.0
        type: linear
      hidden_layers:
        number:
          dueling: 2
          intersection: 1
          intersection_encoder: 2
          lane: 1
          lane_encoder: 2
          lanes: 1
          road: 1
          road_encoder: 2
          roads: 1
          vehicle_encoder: 2
          vehicles: 1
    type: proto
  duration_steps: 5
  framework:
    apex:
      buffer:
        file_capacity: 10000
        size: 200000
      td_steps: 1
    type: apex
  reward:
    common:
      gamma: 0.8
    type: waiting_vehicles
    waiting_vehicles:
      bonus:
        movement: 0.1
        pass: 1.0
      scaler:
        tanh:
          alpha: 3
        tanh_linear:
          alpha: 3
        type: tanh_linear
      weight:
        exponential:
          half: 50
        type: queue_exponential
  state:
    intersection:
      phase: true
    lane:
      length: true
      num_vehicles: true
      type: true
    road:
      delay: true
      queue: true
      route: true
      inflow: true
    vehicle:
      number: 10
      position: false
      speed: false
      route: false
  shape:
  - 2
  - 2
  - 2
  - 2