figure:
  performance_metric: average_queue # average_queue, average_delay, max_queue, max_delay, calc_time
  wild_card_type: num_phases # num_phases only
  plot_flg:
    mpc: true
    scoot: true

mpc:
  horizon: 5                   # predictive horizon
  utilize_steps: 2             # number of steps acutually used in optimized steps (<= horizon / 2)
  remained_steps: 2            # number of remained steps when the optimization starts (<= utilized_steps)
  min_successive_steps: 4      # minimum steps for consecutive phases
  num_max_changes: 1           # maximum number of phase changes within a single optimization 
  branch_gap: 1                # to avoid errors between vissim and mpc regarding the branching point
  bc_buffer: 
    flg: false                  # flg of saving data for behavioral cloning
    size: 1000                  # size of dataset for each buffer file
    network_id: 1               # network architecture id for behavioral cloning
  phases:
    3-road: 4                     # only 4
    4-road: 4                     # 4, 8, or 17
    5-road: 10                    # only 10
  objective_function:
    type: waiting_vehicles        # only waiting_vehicles
    waiting_vehicles:
      definition: 2        # 1: delta_q2 is calculated with using delta_p, 2: delta_q2 is calculated without using delta_p
      range_type: common        # common: use common range for all roads, separate: use separate range for each route 
      queue_measurement:
        type: ema                 # vissim: use vissim's built-in function, ema: use exponential moving average
        ema:  
          alpha: 0.3
      leader_detection:
        type: multiple                 # single: detect leader vehicle from the lane which the car go out, multiple: detect leader vehicle from multiple lanes
    signal_change:
      type: global                # global: use the signal-change binary for whole intersection, local: use the signal-change binary for each route
      weight: 10                  # weights for the term of signal change penalty

scoot:
  initial_parameters:          
    cycle: 40                  # initial cycle time (step)
    split: [10, 10, 10, 10]    # initial split for each phase (step)
  change_steps:
    cycle: 1                   # change amount of cycle time (step)
    split: 1                   # cahnge amount of split (step)
  max_cycle: 60                # max cycle time (step)
  min_split: 4                 # min split for each phase (step)
  spacing_threshold: 20        # spacing threshold for deciding whether increase or decrease cycle time